library(readr)
library(tidyverse)
library(here)
library(janitor)
library(skimr)
df_daily_activity <- read_csv("/cloud/project/raw_data_bellabeat/dailyActivity_merged.csv")
df_daily_calories <- read_csv("/cloud/project/raw_data_bellabeat/dailyCalories_merged.csv")
df_daily_intensities <- read_csv("/cloud/project/raw_data_bellabeat/dailyIntensities_merged.csv")
df_daily_steps <- read_csv("/cloud/project/raw_data_bellabeat/dailySteps_merged.csv")
df_heartrate_seconds <- read_csv("/cloud/project/raw_data_bellabeat/heartrate_seconds_merged.csv")
df_hourly_calories <- read_csv("/cloud/project/raw_data_bellabeat/hourlyCalories_merged.csv")
df_hourly_intensities <- read_csv("/cloud/project/raw_data_bellabeat/hourlyIntensities_merged.csv")
df_hourly_steps <- read_csv("/cloud/project/raw_data_bellabeat/hourlySteps_merged.csv")
df_minute_calories_narrow <- read_csv("/cloud/project/raw_data_bellabeat/minuteCaloriesNarrow_merged.csv")
df_minute_calories_wide <- read_csv("/cloud/project/raw_data_bellabeat/minuteCaloriesWide_merged.csv")
df_minute_intensities_narrow <- read_csv("/cloud/project/raw_data_bellabeat/minuteIntensitiesNarrow_merged.csv")
df_minute_intensities_wide <- read_csv("/cloud/project/raw_data_bellabeat/minuteIntensitiesWide_merged.csv")
df_minute_METs_narrow <- read_csv("/cloud/project/raw_data_bellabeat/minuteMETsNarrow_merged.csv")
df_minute_sleep <- read_csv("/cloud/project/raw_data_bellabeat/minuteSleep_merged.csv")
df_minute_steps_narrow <- read_csv("/cloud/project/raw_data_bellabeat/minuteStepsNarrow_merged.csv")
df_minute_steps_wide <- read_csv("/cloud/project/raw_data_bellabeat/minuteStepsWide_merged.csv")
df_sleep_day <- read_csv("/cloud/project/raw_data_bellabeat/sleepDay_merged.csv")
df_weight_log_info <- read_csv("/cloud/project/raw_data_bellabeat/weightLogInfo_merged.csv")

glimpse(df_daily_activity)